### ISSUE TITLE
Crear rama

### ISSUE THREAD

**Issue by alesalva** [anastudler/TPE-Tio#2]
Crear una rama para agregar texto referente a  "Usos principales de Python"

**Comment by FacundoArguelles** [comment]
listo

**Comment by alesalva** [comment]
Hola chicos, no me funcionó el comando para hacer el milestone
Primero fui al archivo y agregué el texto referido a los bucles y luego en
la consola escribí git commit -m "Agregué bucles" #1 (según mis apuntes de
clase) y me sale el siguiente error:

pathspec '#1' did not match any file(s) known to git.

Perdón chicos, no encuentro la solución. Estoy leyendo para ver qué estoy
haciendo mal.
